import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CheckPoint05",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <div className="bg-green-800 text-white shadow-md py-6 px-4">
          <h1 className="text-2xl md:text-3xl font-bold text-center">
            Catálogo de Produtos!
          </h1>
        </div>
        {children}
      </body>
    </html>
  );
}
